/************************************************************************
*File Name: [File.SQL]
*Author: Dann Hekman (github.com/dannhek)
*Project: [Project Name]
*File Purpose: 
** 		[What this File Does]
*Dependencies:
**		[What other files in this Repo does this file call/need?]
*Dependents:
**		[What other files in this Repo call/need this file?]
*Output Files:
**		[What files does this script create/store?]
*************************************************************************
*Update History:
**[Date] - Created
**[Date] - [Update]
************************************************************************/


